version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli@16.2.9
      - yarn add @angular-devkit/build-angular@16.2.9 --dev
      - echo Installing npm packages
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/runner-route-website