version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - yarn add @angular-devkit/build-angular --dev
      - echo Installing npm packages
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/heart-tracker-website